java -jar target\org.reldb*.jar < test01.sil
java -jar target\org.reldb*.jar < test02.sil
java -jar target\org.reldb*.jar < test03.sil
java -jar target\org.reldb*.jar < test04.sil
java -jar target\org.reldb*.jar < test05.sil
java -jar target\org.reldb*.jar < test06.sil
java -jar target\org.reldb*.jar < test07.sil
java -jar target\org.reldb*.jar < test08.sil
java -jar target\org.reldb*.jar < test09.sil
java -jar target\org.reldb*.jar < test10.sil
java -jar target\org.reldb*.jar < test11.sil
java -jar target\org.reldb*.jar < test12.sil
java -jar target\org.reldb*.jar < test13.sil
java -jar target\org.reldb*.jar < test14.sil