java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test01.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test02.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test03.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test04.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test05.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test06.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test07.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test08.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test09.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test10.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test11.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test12.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test13.sil
java -cp .\target\org.reldb.ldi.silt-0.0.2-SNAPSHOT.jar;"target\lib\*" Silt < test14.sil